# Generated by Django 3.2.3 on 2021-05-31 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameterfile', models.FileField(upload_to='input/')),
                ('microbialfile', models.FileField(upload_to='input/')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationStats',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('bacteria_population', models.BigIntegerField()),
                ('phage_population', models.BigIntegerField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vivaldi.simulation')),
            ],
        ),
    ]
