# Generated by Django 3.2.3 on 2021-05-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vivaldi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationstats',
            name='simulation',
        ),
    ]
