# Generated by Django 3.2.3 on 2021-06-01 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vivaldi', '0002_remove_simulationstats_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulation',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='num_of_sims',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationstats',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='vivaldi.simulation'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='microbialfile',
            field=models.FileField(upload_to='input'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='parameterfile',
            field=models.FileField(upload_to='input'),
        ),
    ]
